name: run ws.py

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalar o python
        uses: actions/setup-python@v4

      - name: instalar os pacotes do requirements.txt
        uses: luisgs7/pip-packages@v1

      - name: executar arquivo de scrapping
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: python ws.py

